#!/usr/bin/env python3
"""Generate main/quotes_data.c from data/quotes_min.json.

PlatformIO espidf builds mishandle EMBED_TXTFILES, so the quote DB is
compiled in as a C array instead (same approach as the fonts).
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "data", "quotes_min.json")
OUT = os.path.join(HERE, "..", "main", "quotes_data.c")

data = open(SRC, "rb").read() + b"\0"   # cJSON needs NUL termination

with open(OUT, "w") as f:
    f.write("// Generated by tools/embed_quotes.py. Do not edit.\n")
    f.write("#include <stddef.h>\n")
    f.write("const char quotes_min_json[] = {\n")
    for i in range(0, len(data), 20):
        f.write("".join("%d," % b for b in data[i:i+20]) + "\n")
    f.write("};\n")
    f.write("const size_t quotes_min_json_len = sizeof(quotes_min_json);\n")

print("wrote %s (%d bytes source data)" % (OUT, len(data)))
