#!/usr/bin/env python3
"""Generate the cat icon as LVGL 9 A8 images, drawn from geometry only.

No external image is read and no third-party library is used: the cat face is
a self-made icon defined as a handful of ellipses and triangles in normalized
(0..1) coordinates, then rasterized twice (72x72 and 48x48) from that single
definition. This replaces the older photo-derived artwork, so nothing here is
a derivative work of any downloaded picture.

Ink rule: head plus ears are ink (alpha 0xFF), eyes and nose are carved back
out to paper (alpha 0x00). No antialiasing, so every byte is 0x00 or 0xFF,
which keeps the glyph legible on the 1-bit reflective panel even at 48 px.

Emits (overwriting):
  ../main/cat_icon.c     cat_icon     72x72
  ../main/cat_icon_48.c  cat_icon_48  48x48
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(HERE, "..", "main")

# --- Shape definition in normalized coordinates (origin top-left, y down) ---

HEAD = (0.50, 0.60, 0.34, 0.30)  # cx, cy, rx, ry

EARS = [
    ((0.22, 0.46), (0.30, 0.12), (0.48, 0.38)),
    ((0.78, 0.46), (0.70, 0.12), (0.52, 0.38)),
]

EYES = [
    (0.38, 0.56, 0.055, 0.080),
    (0.62, 0.56, 0.055, 0.080),
]

NOSE = ((0.50, 0.72), (0.455, 0.655), (0.545, 0.655))


def in_ellipse(x, y, cx, cy, rx, ry):
    dx = (x - cx) / rx
    dy = (y - cy) / ry
    return dx * dx + dy * dy <= 1.0


def in_triangle(x, y, a, b, c):
    def cross(p, q, r):
        return (q[0] - p[0]) * (r[1] - p[1]) - (q[1] - p[1]) * (r[0] - p[0])

    d1 = cross(a, b, (x, y))
    d2 = cross(b, c, (x, y))
    d3 = cross(c, a, (x, y))
    has_neg = d1 < 0 or d2 < 0 or d3 < 0
    has_pos = d1 > 0 or d2 > 0 or d3 > 0
    return not (has_neg and has_pos)


def is_ink(x, y):
    """Return True when the normalized point (x, y) should be ink."""
    solid = in_ellipse(x, y, *HEAD)
    if not solid:
        for ear in EARS:
            if in_triangle(x, y, *ear):
                solid = True
                break
    if not solid:
        return False
    for eye in EYES:
        if in_ellipse(x, y, *eye):
            return False
    if in_triangle(x, y, *NOSE):
        return False
    return True


def render(size):
    """Rasterize the shape definition into a size*size list of 0x00/0xFF."""
    pixels = []
    for row in range(size):
        y = (row + 0.5) / size
        for col in range(size):
            x = (col + 0.5) / size
            pixels.append(0xFF if is_ink(x, y) else 0x00)
    return pixels


def emit_c(path, sym, size, pixels):
    n = size * size
    lines = []
    lines.append("// Generated by tools/make_cat_icon.py. Do not edit by hand.")
    lines.append('#include "lvgl.h"')
    lines.append("")
    lines.append("static const uint8_t %s_map[%d] = {" % (sym, n))
    for row in range(size):
        chunk = pixels[row * size:(row + 1) * size]
        lines.append("    " + " ".join("0x%02X," % v for v in chunk))
    lines.append("};")
    lines.append("")
    lines.append("const lv_image_dsc_t %s = {" % sym)
    lines.append("    .header = {")
    lines.append("        .magic = LV_IMAGE_HEADER_MAGIC,")
    lines.append("        .cf = LV_COLOR_FORMAT_A8,")
    lines.append("        .flags = 0,")
    lines.append("        .w = %d," % size)
    lines.append("        .h = %d," % size)
    lines.append("        .stride = %d," % size)
    lines.append("    },")
    lines.append("    .data_size = %d," % n)
    lines.append("    .data = %s_map," % sym)
    lines.append("};")
    with open(path, "w", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")


def main():
    for sym, size, name in (
        ("cat_icon", 72, "cat_icon.c"),
        ("cat_icon_48", 48, "cat_icon_48.c"),
    ):
        pixels = render(size)
        ink = sum(1 for v in pixels if v == 0xFF)
        path = os.path.join(OUT_DIR, name)
        emit_c(path, sym, size, pixels)
        print("%s: %dx%d, ink %d/%d (%.1f%%)"
              % (name, size, size, ink, len(pixels), 100.0 * ink / len(pixels)))


if __name__ == "__main__":
    main()
